/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RepricingRuleService } from "../repricingRule.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RepricingRuleCreateInput } from "./RepricingRuleCreateInput";
import { RepricingRule } from "./RepricingRule";
import { RepricingRuleFindManyArgs } from "./RepricingRuleFindManyArgs";
import { RepricingRuleWhereUniqueInput } from "./RepricingRuleWhereUniqueInput";
import { RepricingRuleUpdateInput } from "./RepricingRuleUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RepricingRuleControllerBase {
  constructor(
    protected readonly service: RepricingRuleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RepricingRule })
  @nestAccessControl.UseRoles({
    resource: "RepricingRule",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRepricingRule(
    @common.Body() data: RepricingRuleCreateInput
  ): Promise<RepricingRule> {
    return await this.service.createRepricingRule({
      data: {
        ...data,

        product: data.product
          ? {
              connect: data.product,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        maximumPrice: true,
        minimumPrice: true,

        product: {
          select: {
            id: true,
          },
        },

        ruleDescription: true,
        targetProfitMargin: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [RepricingRule] })
  @ApiNestedQuery(RepricingRuleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RepricingRule",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async repricingRules(
    @common.Req() request: Request
  ): Promise<RepricingRule[]> {
    const args = plainToClass(RepricingRuleFindManyArgs, request.query);
    return this.service.repricingRules({
      ...args,
      select: {
        createdAt: true,
        id: true,
        maximumPrice: true,
        minimumPrice: true,

        product: {
          select: {
            id: true,
          },
        },

        ruleDescription: true,
        targetProfitMargin: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RepricingRule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RepricingRule",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async repricingRule(
    @common.Param() params: RepricingRuleWhereUniqueInput
  ): Promise<RepricingRule | null> {
    const result = await this.service.repricingRule({
      where: params,
      select: {
        createdAt: true,
        id: true,
        maximumPrice: true,
        minimumPrice: true,

        product: {
          select: {
            id: true,
          },
        },

        ruleDescription: true,
        targetProfitMargin: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RepricingRule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RepricingRule",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRepricingRule(
    @common.Param() params: RepricingRuleWhereUniqueInput,
    @common.Body() data: RepricingRuleUpdateInput
  ): Promise<RepricingRule | null> {
    try {
      return await this.service.updateRepricingRule({
        where: params,
        data: {
          ...data,

          product: data.product
            ? {
                connect: data.product,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          maximumPrice: true,
          minimumPrice: true,

          product: {
            select: {
              id: true,
            },
          },

          ruleDescription: true,
          targetProfitMargin: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RepricingRule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RepricingRule",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRepricingRule(
    @common.Param() params: RepricingRuleWhereUniqueInput
  ): Promise<RepricingRule | null> {
    try {
      return await this.service.deleteRepricingRule({
        where: params,
        select: {
          createdAt: true,
          id: true,
          maximumPrice: true,
          minimumPrice: true,

          product: {
            select: {
              id: true,
            },
          },

          ruleDescription: true,
          targetProfitMargin: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
