/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsBoolean,
  IsOptional,
  ValidateNested,
  IsNumber,
  Min,
  Max,
  IsString,
  MaxLength,
  IsInt,
} from "class-validator";

import { CompetitorUpdateManyWithoutProductsInput } from "./CompetitorUpdateManyWithoutProductsInput";
import { Type } from "class-transformer";
import { PerformanceReportUpdateManyWithoutProductsInput } from "./PerformanceReportUpdateManyWithoutProductsInput";
import { RepricingRuleUpdateManyWithoutProductsInput } from "./RepricingRuleUpdateManyWithoutProductsInput";

@InputType()
class ProductUpdateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  buyBoxStatus?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => CompetitorUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => CompetitorUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => CompetitorUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  competitors?: CompetitorUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  currentPrice?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => PerformanceReportUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => PerformanceReportUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => PerformanceReportUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  performanceReports?: PerformanceReportUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => RepricingRuleUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => RepricingRuleUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => RepricingRuleUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  repricingRules?: RepricingRuleUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  stockLevel?: number | null;
}

export { ProductUpdateInput as ProductUpdateInput };
