/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProductService } from "../product.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductCreateInput } from "./ProductCreateInput";
import { Product } from "./Product";
import { ProductFindManyArgs } from "./ProductFindManyArgs";
import { ProductWhereUniqueInput } from "./ProductWhereUniqueInput";
import { ProductUpdateInput } from "./ProductUpdateInput";
import { CompetitorFindManyArgs } from "../../competitor/base/CompetitorFindManyArgs";
import { Competitor } from "../../competitor/base/Competitor";
import { CompetitorWhereUniqueInput } from "../../competitor/base/CompetitorWhereUniqueInput";
import { PerformanceReportFindManyArgs } from "../../performanceReport/base/PerformanceReportFindManyArgs";
import { PerformanceReport } from "../../performanceReport/base/PerformanceReport";
import { PerformanceReportWhereUniqueInput } from "../../performanceReport/base/PerformanceReportWhereUniqueInput";
import { RepricingRuleFindManyArgs } from "../../repricingRule/base/RepricingRuleFindManyArgs";
import { RepricingRule } from "../../repricingRule/base/RepricingRule";
import { RepricingRuleWhereUniqueInput } from "../../repricingRule/base/RepricingRuleWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProductControllerBase {
  constructor(
    protected readonly service: ProductService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Product })
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProduct(
    @common.Body() data: ProductCreateInput
  ): Promise<Product> {
    return await this.service.createProduct({
      data: data,
      select: {
        buyBoxStatus: true,
        createdAt: true,
        currentPrice: true,
        id: true,
        name: true,
        stockLevel: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Product] })
  @ApiNestedQuery(ProductFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async products(@common.Req() request: Request): Promise<Product[]> {
    const args = plainToClass(ProductFindManyArgs, request.query);
    return this.service.products({
      ...args,
      select: {
        buyBoxStatus: true,
        createdAt: true,
        currentPrice: true,
        id: true,
        name: true,
        stockLevel: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async product(
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Product | null> {
    const result = await this.service.product({
      where: params,
      select: {
        buyBoxStatus: true,
        createdAt: true,
        currentPrice: true,
        id: true,
        name: true,
        stockLevel: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProduct(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() data: ProductUpdateInput
  ): Promise<Product | null> {
    try {
      return await this.service.updateProduct({
        where: params,
        data: data,
        select: {
          buyBoxStatus: true,
          createdAt: true,
          currentPrice: true,
          id: true,
          name: true,
          stockLevel: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProduct(
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Product | null> {
    try {
      return await this.service.deleteProduct({
        where: params,
        select: {
          buyBoxStatus: true,
          createdAt: true,
          currentPrice: true,
          id: true,
          name: true,
          stockLevel: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/competitors")
  @ApiNestedQuery(CompetitorFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Competitor",
    action: "read",
    possession: "any",
  })
  async findCompetitors(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Competitor[]> {
    const query = plainToClass(CompetitorFindManyArgs, request.query);
    const results = await this.service.findCompetitors(params.id, {
      ...query,
      select: {
        competitorPrice: true,
        createdAt: true,
        id: true,
        marketCondition: true,

        product: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/competitors")
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  async connectCompetitors(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: CompetitorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      competitors: {
        connect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/competitors")
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  async updateCompetitors(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: CompetitorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      competitors: {
        set: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/competitors")
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  async disconnectCompetitors(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: CompetitorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      competitors: {
        disconnect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/performanceReports")
  @ApiNestedQuery(PerformanceReportFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PerformanceReport",
    action: "read",
    possession: "any",
  })
  async findPerformanceReports(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<PerformanceReport[]> {
    const query = plainToClass(PerformanceReportFindManyArgs, request.query);
    const results = await this.service.findPerformanceReports(params.id, {
      ...query,
      select: {
        competitorAnalysis: true,
        createdAt: true,
        id: true,
        pricingHistory: true,

        product: {
          select: {
            id: true,
          },
        },

        sales: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/performanceReports")
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  async connectPerformanceReports(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: PerformanceReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      performanceReports: {
        connect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/performanceReports")
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  async updatePerformanceReports(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: PerformanceReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      performanceReports: {
        set: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/performanceReports")
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  async disconnectPerformanceReports(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: PerformanceReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      performanceReports: {
        disconnect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/repricingRules")
  @ApiNestedQuery(RepricingRuleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RepricingRule",
    action: "read",
    possession: "any",
  })
  async findRepricingRules(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<RepricingRule[]> {
    const query = plainToClass(RepricingRuleFindManyArgs, request.query);
    const results = await this.service.findRepricingRules(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        maximumPrice: true,
        minimumPrice: true,

        product: {
          select: {
            id: true,
          },
        },

        ruleDescription: true,
        targetProfitMargin: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/repricingRules")
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  async connectRepricingRules(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: RepricingRuleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      repricingRules: {
        connect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/repricingRules")
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  async updateRepricingRules(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: RepricingRuleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      repricingRules: {
        set: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/repricingRules")
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "update",
    possession: "any",
  })
  async disconnectRepricingRules(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: RepricingRuleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      repricingRules: {
        disconnect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }
}
