/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsBoolean,
  IsOptional,
  ValidateNested,
  IsDate,
  IsNumber,
  Min,
  Max,
  IsString,
  MaxLength,
  IsInt,
} from "class-validator";

import { Competitor } from "../../competitor/base/Competitor";
import { Type } from "class-transformer";
import { PerformanceReport } from "../../performanceReport/base/PerformanceReport";
import { RepricingRule } from "../../repricingRule/base/RepricingRule";

@ObjectType()
class Product {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  buyBoxStatus!: boolean | null;

  @ApiProperty({
    required: false,
    type: () => [Competitor],
  })
  @ValidateNested()
  @Type(() => Competitor)
  @IsOptional()
  competitors?: Array<Competitor>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  currentPrice!: number | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: () => [PerformanceReport],
  })
  @ValidateNested()
  @Type(() => PerformanceReport)
  @IsOptional()
  performanceReports?: Array<PerformanceReport>;

  @ApiProperty({
    required: false,
    type: () => [RepricingRule],
  })
  @ValidateNested()
  @Type(() => RepricingRule)
  @IsOptional()
  repricingRules?: Array<RepricingRule>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  stockLevel!: number | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Product as Product };
