/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsBoolean,
  IsOptional,
  ValidateNested,
  IsNumber,
  Min,
  Max,
  IsString,
  MaxLength,
  IsInt,
} from "class-validator";

import { CompetitorCreateNestedManyWithoutProductsInput } from "./CompetitorCreateNestedManyWithoutProductsInput";
import { Type } from "class-transformer";
import { PerformanceReportCreateNestedManyWithoutProductsInput } from "./PerformanceReportCreateNestedManyWithoutProductsInput";
import { RepricingRuleCreateNestedManyWithoutProductsInput } from "./RepricingRuleCreateNestedManyWithoutProductsInput";

@InputType()
class ProductCreateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  buyBoxStatus?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => CompetitorCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => CompetitorCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => CompetitorCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  competitors?: CompetitorCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  currentPrice?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => PerformanceReportCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => PerformanceReportCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => PerformanceReportCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  performanceReports?: PerformanceReportCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => RepricingRuleCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => RepricingRuleCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => RepricingRuleCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  repricingRules?: RepricingRuleCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  stockLevel?: number | null;
}

export { ProductCreateInput as ProductCreateInput };
